@startuml light_creation
autoactivate on
hide footbox
participant App

create DirectionalLight
App -> DirectionalLight : <<create>>
create UniformBuffer
DirectionalLight -> UniformBuffer : <<create>>
return
return

@enduml